### ISSUE TITLE
Songrec need libssl1.1 on Ubuntu 22.04

### ISSUE THREAD

**Issue by fredericpetit02** [marin-m/SongRec#102]
Hi,

On Ubuntu 22.04, the package depends libssl1.1, but it's not available.

**Comment by yeboahnanaosei** [comment]
Same issue here. I am unable to install using `sudo apt install songrec -y`
![Screenshot_2022-07-01_01-10-43](https://user-images.githubusercontent.com/22800157/176803088-5c9ffafa-9e74-4cbb-b150-485f6d1d089d.png)

**Comment by marin-m** [comment]
Hello,

@fredericpetit02 @yeboahnanaosei Does installing the package under Ubuntu ≥ 22.04 works better now? (I have updated the upstream Ubuntu package to version `0.3.2+1`)

Regards,

**Comment by fredericpetit02** [comment]
> @fredericpetit02 @yeboahnanaosei Does installing the package under Ubuntu ≥ 22.04 works better now? (I have updated the upstream Ubuntu package to version `0.3.2+1`)

Yes ! ;)
