### ISSUE TITLE
Songrec does not have access to my speakers

### ISSUE THREAD

**Issue by Bundy01** [marin-m/SongRec#103]
Hi,

My bluetooth speakers are not accessible with Songrec. No problem with the ones integrated on my laptop.

Will it be possible to integrate bluetooth and wifi speakers?

Regards.

**Comment by awsms** [comment]
Same with pipewire here. Songrec only recognizes the integrated speaker, regardless the active one set in pipewire.

**Comment by Toorero** [comment]
I have the same issue. Currently, my **workaround** is to use [Helvum](https://gitlab.freedesktop.org/pipewire/helvum) to rewire it to my Bluetooth headphones. I think you could automate this with udev rules or using internal Pipewire configs but I don't really care and don't know either how to do so.

 **Before**
![grafik](https://user-images.githubusercontent.com/22551563/184650420-70fab453-98ca-411c-a009-b083734adb6e.png)
**After**
![grafik](https://user-images.githubusercontent.com/22551563/184650510-1d79fd8a-f4d4-4368-8a77-a6a4b7cfa2e3.png)

**Comment by marin-m** [comment]
Hello,

Thanks for reporting. I think that a correct way to ensure PipeWire compatibility and fix these issues could be to rewrite the audio interfacing part of the application in order to the use the GStreamer library instead of `rodio` (which has an ALSA-based backend and natively supports less formats, we already support interfacing with FFmpeg when available to circumvent this last issue).

Contributions are welcome on this is anyone would wish to get involved

Regards,

**Comment by georgefst** [comment]
Yeah, I have this same issue, and have also been working around it with Helvum. As far as I can tell, SongRec picks an output to monitor at random - it's certainly not always (in fact, IME, ever) the one that's currently active.

It might be best if individual outputs appeared as entries within SongRec's "Audio input" dropwdown. Indeed, this may already be the case for ALSA, since I see a `sysdefault:CARD=sofhdadsp` entry.

I'm using `pipewire-pulse`, which exposes the same API as PulseAudio, so SongRec should work very similarly to how it does with normal PulseAudio. I seem to get exactly the same behaviour regardless of whether I set SongRec's audio input to `pipewire` or `pulse`.

**Comment by BeyondMagic** [comment]
Songrec doesn't even open for me, nor display any errors.

I am pretty sure it's the lack of pipewire support, but not sure how fix it with Helvum. Could you give some explanation how to, @georgefst?

**Comment by georgefst** [comment]
If Songrec doesn't even start, I don't think Helvum can help you.

**Comment by georgefst** [comment]
> Yeah, I have this same issue, and have also been working around it with Helvum.

Got fed up of patching this manually every time, so I wrote a (needlessly robust and general) script:
```sh
#!/bin/bash

# tell Songrec to monitor the system's default output

export SONGREC_BINARY_NAME=songrec

pw-dump > /tmp/pw-dump.json

export DEFAULT_SINK=$(cat /tmp/pw-dump.json | jq -r 'map(select(.type == "PipeWire:Interface:Metadata")) | map(.metadata) | flatten | map(select(.key == "default.audio.sink")) | map(.value.name) | .[]')
echo $DEFAULT_SINK

export DEFAULT_SINK_NODE_ID=$(cat /tmp/pw-dump.json | jq -r 'map(select(.type == "PipeWire:Interface:Node")) | map(select(.info.props."node.name" == env.DEFAULT_SINK)) | .[] | .id')
echo $DEFAULT_SINK_NODE_ID

cat /tmp/pw-dump.json | jq -r 'map(select(.type == "PipeWire:Interface:Port")) | map(select(.info.props."node.id" == (env.DEFAULT_SINK_NODE_ID|tonumber))) | map(select(.info.props."port.monitor"))' > /tmp/pw-default-sink-ports.json
cat /tmp/pw-default-sink-ports.json | jq -r 'map(.info.props."object.path") | .[]'

export SONGREC_NODE_ID=$(cat /tmp/pw-dump.json | jq -r 'map(select(.type == "PipeWire:Interface:Node")) | map(select(.info.props."application.process.binary" == "songrec")) | .[] | .id')
echo $SONGREC_NODE_ID

cat /tmp/pw-dump.json | jq -r 'map(select(.type == "PipeWire:Interface:Port")) | map(select(.info.props."node.id" == (env.SONGREC_NODE_ID|tonumber))) | map(select(.info.direction == "input"))' > /tmp/pw-songrec-input-ports.json
cat /tmp/pw-songrec-input-ports.json | jq -r 'map(.info.props."object.path") | .[]'

for ((i=0; ;++i))
do
    export INDEX=$i
    IN=$(cat /tmp/pw-default-sink-ports.json | jq -r 'map(select(.info.props."port.id" == (env.INDEX|tonumber))) | .[].info.props."object.path"')
    echo $IN
    OUT=$(cat /tmp/pw-songrec-input-ports.json | jq -r 'map(select(.info.props."port.id" == (env.INDEX|tonumber))) | .[].info.props."object.path"')
    echo $OUT
    if [[ -n "$IN" && -n "$OUT" ]] && pw-link "$IN" "$OUT" ; then echo "linked" ; else break ; fi
done
```

https://xkcd.com/974/

**Comment by Darukutsu** [comment]
I'm not sure if this is related to this issue but I had same problem using bluetooth earphones. I wrote script after reading issue #58 to stop doing this manually when using different device: 

`#!/bin/sh

# recognizes only one song then exits
nohup songrec recognize -d default > shazam.txt &

# need to wait before songrec init
sleep 1

# expecting there will be only songrec
SOURCE_OUTPUT_ID=$(pactl list short source-outputs | cut -d$'\t' -f1)

# list sources and then pick one (type number)
pactl list short sources
read SOURCE_ID

pactl move-source-output "$SOURCE_OUTPUT_ID" "$SOURCE_ID"

# wait until recognizes
wait

cat shazam.txt && rm shazam.txt
`
then:
`alias mysongrec=/path/to/this_script.sh`

I'm using songrec 0.3.2 version from pacman. Pipewire 0.3.63

**Comment by Bundy01** [comment]
Thank you @marin-m for considering my request :)
It's work now.

**Comment by georgefst** [comment]
@Bundy01 Could you explain what has changed?

I'm not convinced this issue should be closed. In general, it seems Songrec's logic for choosing which output to connect to could be a lot better.

**Comment by Bundy01** [comment]
@georgefst 
with Songrec version 0.4.2, you can choose your Bluetooth speakers in "Sound input".
That's a big step forward.

**Comment by georgefst** [comment]
Not for me! Maybe I'll just open a separate issue.
