### ISSUE TITLE
PPA pub key (Ubuntu 22.04)

### ISSUE THREAD

**Issue by terr72** [marin-m/SongRec#112]
After updating to Ubuntu 22.04 the package management complains about the public key being stored in a deprecated way via apt-key.

Can you point to the URI where the Songrec PPA pub key is being stored, so that I can add it manually using the new method?
It might also be helpful for other users to update the PPA installation procedure for Ubuntu on the main page.

**Comment by DaAxe** [comment]
I would also like to have this pub key. currently get the error:
"  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6888550B2FC77D09"
When following the apt instructions on main page.

**Comment by marin-m** [comment]
Hello,

Does using this command do well?

```
wget -qO- 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x6888550b2fc77d09' | sudo tee /etc/apt/trusted.gpg.d/songrec.asc
```

Regards,

**Comment by terr72** [comment]
> Does using this command do well?

Yes, worked fine.
