### ISSUE TITLE
Odd bug causing Firefox right click and menus in general to stop working

### ISSUE THREAD

**Issue by CHJ85** [marin-m/SongRec#13]
Hi there. After I open SoundRec, menus in Firefox stops working.
What kind of odd bug is this and is there a fix for this other than restarting Firefox?
I'm using Kubuntu btw.

**Comment by marin-m** [comment]
Hello,

I did not heard of this, through which mean did you install SongRec? (GNOME Software, Flatpak, PPA, etc.) Also, which Linux distribution do you use?

**Comment by CHJ85** [comment]
The PPA, version 0.1.2.

**Comment by x16** [comment]
Having the same issue for the last 10 months. Very annoying... Have to restart Firefox after every SongRec session.

**Comment by CHJ85** [comment]
@x16 Yup. I ended up installing the Flatpak version instead.

**Comment by ducaton** [comment]
Filled the bug in Bugzilla. At that time, I thought that it caused not only by SongSec, but by some browser error. Now in doubt.
https://bugzilla.mozilla.org/show_bug.cgi?id=1766068
Arch Linux, SongSec installed from community repository.

**Comment by marin-m** [comment]
Hello!

Closing as pull request #100 now avoids reproducing this issue in SongRec

Regards,
