### ISSUE TITLE
Songrec crashes when using buttons

### ISSUE THREAD

**Issue by yataghan012** [marin-m/SongRec#140]
It looks like a ran out of space in my main partition temporarily and maybe some file corrupted?

I can't use songrec at all, anymore. Doesn't show my input selection (back to default) and there's no song list. I can only use the buttons that allows me to select a file/location, but nothing after that.

I'm on Manjaro, latest Linux LTS kernel. Latest songrec version. I tried reinstalling, and using flatpak version.

**Comment by marin-m** [comment]
Hello,

Maybe that deleting the `$HOME/.local/share/SongRec/` folder could help?

Regards,

**Comment by yataghan012** [comment]
> Hello,
> 
> Maybe that deleting the `$HOME/.local/share/SongRec/` folder could help?
> 
> Regards,

Hello, thanks for replying.

It doesn't work.

**Comment by marin-m** [comment]
Re,

The Flatpak version doesn't use the same file opening mechanism as the non-containerized version. It is better running SongRec from a non-Flatpak source (distribution package, Cargo, compiling from the source, etc.) when trying to reproducing the bug.

Does anything appears in the console when running `songrec` from the command line and picking the file?

**Comment by marin-m** [comment]
It seems that the communication with your audio backend (likely PipeWire emulating ALSA) does not work.

Does the same issue happen when running SongRec as root (using `sudo`)?

Can you record sound using your microphone with other apps (e.g. Audacity, your browser...)?

**Comment by yataghan012** [comment]
> It seems that the communication with your audio backend (likely PipeWire emulating ALSA) does not work.
> 
> Does the same issue happen when running SongRec as root (using `sudo`)?
> 
> Can you record sound using your microphone with other apps (e.g. Audacity, your browser...)?

It doesn't crash as root, but there are no audio inputs that work like before (they all say GENERIC). I only used songrec for sound from my computer.

Inboard audio does work for audacity under "default".

**Comment by yataghan012** [comment]
> It seems that the communication with your audio backend (likely PipeWire emulating ALSA) does not work.
> 
> Does the same issue happen when running SongRec as root (using `sudo`)?
> 
> Can you record sound using your microphone with other apps (e.g. Audacity, your browser...)?

Hello?

**Comment by marin-m** [comment]
It may be linked with PipeWire compatibility (and/or the compatibility layers of newer versions of PipeWire being buggy).

I should setup a new virtual machine with a recent software stack someday to test this (note: this is a side project, I also have a full-time job besides this and contributions are welcome)

**Comment by yataghan012** [comment]
> It may be linked with PipeWire compatibility (and/or the compatibility layers of newer versions of PipeWire being buggy).
> 
> I should setup a new testing environment with a recent software stack someday to test this (note: this is a side project, I also have a full-time job besides this and contributions are welcome)

Not I managed to get it working using the flatpak version (0.4.0) the other version I was using that didn't work was from the official manjaro repositories (0.3.3-1)

**Comment by aktaboot** [comment]
probably same issue as #155
