### ISSUE TITLE
Cast of negative values to unsinged int in rust version

### ISSUE THREAD

**Issue by punkt2** [marin-m/SongRec#143]
Hi,

I was investigating why the rust version generates a different signature than the python version with the same input file.

I found that the rust version casts `peak_variation_2` from `float` to `unsigned int`. This causes negative values to become zero before being added to `bin_position`. Is this intended?
The python version does not do this casting.

Rust:

https://github.com/marin-m/SongRec/blob/5dab35e5be1233b7342c44ce0fdf805ff0e17b96/src/fingerprinting/algorithm.rs#L252-L254

Python:
https://github.com/marin-m/SongRec/blob/5dab35e5be1233b7342c44ce0fdf805ff0e17b96/python-version/fingerprinting/algorithm.py#L237-L239

**Comment by marin-m** [comment]
I was not sure about this casting behavior from Rust, I modified it, thanks
