### ISSUE TITLE
"Audio input" options don't work

### ISSUE THREAD

**Issue by dln949** [marin-m/SongRec#149]
The only way I can get SongRec to work for online streaming music is to have microphone recognition on.  Using the "Audio input" options when microphone recognition is off does not work, and appears to have no effect when microphone recognition is on.  

SongRec flatpak version 0.4.1

Ubuntu 22.04.3

**Comment by dln949** [comment]
Ok, thanks.  

So then, what combination of settings should I be using to with a live stream of music from the internet on my computer?

**Comment by marin-m** [comment]
Just keep the live recognition on check the "recognize from my speakers instead of microphones" checkbox on. There is a sound level indicator on the UI (above the audio input selection list) that should indicate you whether sound is being input to SongRec or not.

**Comment by dln949** [comment]
Oh, so the way I understand this:  

If I want to record from a live, physically present audio source, I rely on the microphone recognition only being on.  

But if I want SongRec to analyze live streaming music coming into my computer, I need to enable BOTH "Recognize from my speakers instead of microphone" AND keep microphone recognition set to "on".  Is that correct?  (The phrase "instead of microphone" made me think that I needed to keep the microphone recognition "off".)

**Comment by marin-m** [comment]
Yes
