### ISSUE TITLE
Generic icon in dock when running

### ISSUE THREAD

**Issue by heldderarbeit** [marin-m/SongRec#162]
When running the app in wayland, the icon is missing in the GNOME dock:

![image](https://github.com/marin-m/SongRec/assets/4840355/670a80ca-78dd-485c-bb7a-21aa011d8d45)

Investigating through Looking Glass, it becomes apparent the field for "app" is not set:

![image](https://github.com/marin-m/SongRec/assets/4840355/359cfc21-f983-4b70-b219-2fcc85be02c9)

Solution for this is to add a line with "StartupWMClass=songrec" to the Desktop file.

Here is a bit more info about this known issue: https://ubuntuhandbook.org/index.php/2024/04/missing-icon-dock-ubuntu-2404/

**Comment by marin-m** [comment]
Thank you, PR #163 has been merged and released so I'm closing this issue
