### ISSUE TITLE
[Bug] Cannot remove just-added track from Favorites popup

### ISSUE THREAD

**Issue by lonix1** [marin-m/SongRec#178]
One cannot remove a just-added track from the "Favorites" popup. To remove it, one must reopen the app.

Repro:
- recognise something
- right click > "Add to Favorites"
- click Favorites ...favorites popup shows
- right click just-added track - context menu does not show "Remove from Favorites"
- close app, reopen
- click Favorites ...favorites popup shows
- right click track - context menu shows "Remove from Favorites"

**Comment by damonhayhurst** [comment]
#179 Fix here

**Comment by marin-m** [comment]
Fix merged and released
