### ISSUE TITLE
SongRec can't be closed by Ctrl+Q

### ISSUE THREAD

**Issue by toboil-features** [marin-m/SongRec#181]
I wish SongRec can be closed by using that shortcut, so my habit will stay with me.

![Showcase](https://github.com/user-attachments/assets/037e8ecd-af01-4ac3-be69-113a05129abe)

**Comment by Real-Packet** [comment]
This would be easy to implement. Just check if we're pressing <kbd>Q</kbd> and check if we're also holding <kbd>Ctrl</kbd>, if so, exit.

**Comment by marin-m** [comment]
This has been implemented, thanks!
