### ISSUE TITLE
algorithm is too slow

### ISSUE THREAD

**Issue by zhiying8710** [marin-m/SongRec#20]
Awsome project!
I'm using python version, function `do_peak_spreading` cost over 4 seconds every time.
any idea to improve it? thank you.

**Comment by marin-m** [comment]
Hello,

The intent of rewriting the project to Rust was to improve the performance of the algorithm.

To optimize further the Python version, you may try, for example, one of these options:

* Write a [C/Python module](https://docs.python.org/3/extending/extending.html) where to put the core of the algorithm
* Use another language that may be faster such as Java
* Try to simplify the algorithm, but without guarantee to see the same results
* Try to use an alternative Python runtime such as [Numba](https://en.wikipedia.org/wiki/Numba)

Regards,

**Comment by zhiying8710** [comment]
thanks for reply!
I'm using java version now, it's much faster than python.
