### ISSUE TITLE
Capture output audio stream as source

### ISSUE THREAD

**Issue by Ellipse0934** [marin-m/SongRec#26]
It would be nice to have the software pickup audio from the output stream. 
Often while watching a movie or a twitch stream I would like to know the song which is playing and headphones -> mic isn't the best solution.

I guess this may be hard to implement but still a nice to have.

**Comment by mark0100** [comment]
I agree with you. I already opened an Idea/Discussion about this a couple of days ago.

**Comment by Ellipse0934** [comment]
Duplicate of #24. Closing. 

Apologies.
