### ISSUE TITLE
What data it collects?

### ISSUE THREAD

**Issue by TROMsite** [marin-m/SongRec#32]
As I understand this talks to Shazam's servers, it so what data does it collects about me?

**Comment by marin-m** [comment]
Hello,

SongRec collects no data and contacts no other servers than Shazam's. SongRec does not upload raw audio data anywhere: only fingerprints of the audio are uploaded, which means sequences of frequency peaks encoded in the form of "(frequency, amplitude, time)" tuples.

This does not suffice to represent anything hearable alone (use the "Play a Shazam lure" button to see how much this is different from full sound); that means that no actually hearable sound (e.g voice fragments) is sent to servers, only metadata derived on the characteristics of the sound that may only suffice to recognize a song already known by Shazam is being sent.

Thanks for asking, it made me think to add it to the README (commit c4eda4b)

Regards,
