### ISSUE TITLE
HTTP error spam

### ISSUE THREAD

**Issue by Douile** [marin-m/SongRec#37]
**Bug description**:
When network cuts out or there is some other API error, the user is spammed with an error dialog every time a request is sent.

The particular message I was getting was along the lines of (not exactly this):
```
Unable to decode JSON
Unexpected token at line 2 position 0
```
```
error decoding response body: EOF while parsing a value at line 1 column 0
```

**Expected behavior**:
Either:
- API errors are logged to terminal, file or somplace else.
- Error dialogs are ignored if the last error message is the same as the next one
- Some way to disable error dialogs

**Version**: 
songrec: 0.1.6-1 (AUR)

**Relevant code**:

https://github.com/marin-m/SongRec/blob/0d9662512a3e9a0e5bca6060269aad941d707d13/src/gui/http_thread.rs#L66-L68

https://github.com/marin-m/SongRec/blob/0d9662512a3e9a0e5bca6060269aad941d707d13/src/gui/main_window.rs#L428-L437

Great project by the way :)

**Comment by marin-m** [comment]
Hello,

Thanks for creating the issue, it's true that it may be inconvenient e.g when quitting hibernation.

Here is what will show on the main window when having been offline recently, after commit 9267feb 

![image](https://user-images.githubusercontent.com/25437947/113672726-63f3c100-96b8-11eb-8068-b636e86fc8f5.png)

**Comment by Douile** [comment]
Thanks!
