### ISSUE TITLE
Consider tracking Cargo.lock

### ISSUE THREAD

**Issue by tcbravo** [marin-m/SongRec#43]
Thanks for your work on this tool, it's great to have something like this available on the desktop.

One very small issue, though: the project's `Cargo.lock` file is currently not tracked since it's listed in `.gitignore`. Would you consider adding it to the repository? This is the approach recommended by the [Cargo book](https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html) for "end product"-type software, such as applications (emphasis mine):

> If you’re building a non-end product, such as a rust library that other rust packages will depend on, put Cargo.lock in your .gitignore. **If you’re building an end product, which are executable like command-line tool or an application**, or a system library with crate-type of staticlib or cdylib, **check Cargo.lock into git**. If you're curious about why that is, see ["Why do binaries have Cargo.lock in version control, but not libraries?"](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries) in the FAQ.

Having the lockfile available would bring reproducibility benefits for distributions which package SongRec, since they would be able to ensure builds use the exact same set of dependencies as upstream. (I'm also considering packaging SongRec in [nixpkgs](https://github.com/NixOS/nixpkgs), which more or less requires having this level of reproducibility for packages to be accepted.)

**Comment by marin-m** [comment]
Hello,

Thanks you for the suggestion, I have pushed a release 0.1.8 to Github that includes the change.

Regards
