### ISSUE TITLE
Flatpak packaging

### ISSUE THREAD

**Issue by pedrofleck** [marin-m/SongRec#5]
Your app does look good, but having to compile it makes it difficult for people to try it out. Maybe flatpak packaging could help people in multiple distros (except for Ubuntu) to easily test it.
Thanks!

**Comment by marin-m** [comment]
Thanks for the suggestion. Pull request to Flathub sent.

I think that I should work on handling Snap or maybe DEB soon.

**Comment by bilelmoussaoui** [comment]
Flatpak work in ubuntu as well.

**Comment by pedrofleck** [comment]
@marin-m Thanks a lot!
@bilelmoussaoui I know, but it is not as straightforward as it is in Fedora, Mint, Elementary and others, for example.

**Comment by marin-m** [comment]
FYI, the [Flathub package](https://flathub.org/apps/details/com.github.marinm.songrec) has been published and [installation instructions](https://github.com/marin-m/SongRec#installation) have been updated .

**Comment by marin-m** [comment]
FYI, the [Flathub package](https://flathub.org/apps/details/com.github.marinm.songrec) has been published and [installation instructions](https://github.com/marin-m/SongRec#installation) have been updated accordingly.

I also have create a Launchpad PPA (I have tried to build a Snap package but there seemed to be compatibility issues with `libasound` that cause the application to segfault quickly after its launch, and submitting the app would have required to go through a manual authorization process at least for the sound recording authorization, so for now I think that providing the application in a DEB form for Ubuntu users is better).

**Comment by pedrofleck** [comment]
I just installed it here and it worked just fine (altough I've got some errors with xdg-desktop-portal-gtk when trying to select a file some times, I can report it in a different bug report if you want). Thank you!
