### ISSUE TITLE
continuously updating file with recognition output

### ISSUE THREAD

**Issue by codeskullz** [marin-m/SongRec#51]
Is it possible that there is a default file generated by SongRec that is continuously updated when recognizing a song, I will add this to OBS-studio for the information of my viewers.

**Comment by hg2s** [comment]
Does [this](https://github.com/marin-m/SongRec) address your question? 

> "When using the application, you may notice that certain information will be saved to ~/.local/share/SongRec (or an equivalent directory depending on your operating system), including the **CSV-format list of the last recognized songs** and the last selected microphone input device (so that it is chosen back when restarting the app)."
