### ISSUE TITLE
GUI features but in command-line only?

### ISSUE THREAD

**Issue by carotx** [marin-m/SongRec#55]
Hi,

The continuous song recognition and the history export to csv are great features!
However I would like to run these on a headless server (e.g. rpi with mic connected).

Is there a simple way to run songRec with all these amazing features (continuous recognition and csv export), but from a CLI? Alas I don't know rust at all...

Merci d'avance pour votre aide :)

**Comment by marin-m** [comment]
Hello,

Which distribution does your RPI runs? Does it have ALSA, PulseAudio, JACK installed?

Which output format would you think first best: parsing the standard output, progressively writing to a CSV file, feeding an UNIX socket, other?

Thank you!

**Comment by lbenard** [comment]
I second this! I'd love to be able to just run this from a script and make it automatically listen to what's on my default output.
I think getting the JSON output back (as the `audio-file-to-recognized-song` option does) would do great, especially for scripts.

**Comment by carotx** [comment]
Hi, sorry for the delay :S

Hum I said "rpi" but for now I'm only trying things on an old laptop running debian buster. So I guess ALSA, pulseaudio, etc are not an issue? (on a rpi I would also run a debian).
The purpose is to display the list on a website (keeping it as simple as possible, a simple html page for instance) ... so for the output format: csv, json, or directly in html ... I don't know what's best.

**Comment by hg2s** [comment]
> The purpose is to display the list on a website (keeping it as simple as possible, a simple html page for instance) ... so for the output format: csv, json, or directly in html ... I don't know what's best.

Do you want to display the song metadata as a stream or broadcast is being played?

**Comment by carotx** [comment]
> Do you want to display the song metadata as a stream or broadcast is being played?

I want to display songs that are played in a street ... so kind of a stream, maybe we can say so.

**Comment by hg2s** [comment]
> However I would like to run these on a headless server (e.g. rpi with mic connected).

Can you use a headless video adapter on the RPi? That way you could boot the RPi as normal and it thinks it has a monitor attached. You remote in using VNC, for example, and run the SongRec GUI remotely. 

Do a search on Amazon for "VGA Dummy Plug,Headless Ghost, Display Emulator" and see what I mean.

**Comment by hg2s** [comment]
> However as long as I understand, I would still need to run SongRec on a desktop environment, for instance with gnome. To this point, why wouldn't I just boot with a screen, then unplug it once started and go for vnc? That looks ok for the "headless" part of my problem.

Yes, at present you would still need desktop, and you could start with a display and pull the cable, once started, as long as you don't need to restart. 

> Still, it doesn't solve my second point about having the output not in the GUI, but in a csv/json/socket.

Can you grab the current song title from the history file and use that for your display? 

[READMe](https://github.com/marin-m/SongRec/blob/master/README.md): "When using the application, you may notice that certain information will be saved to ~/.local/share/SongRec (or an equivalent directory depending on your operating system), including the CSV-format list of the last recognized songs and the last selected microphone input device (so that it is chosen back when restarting the app). You may want to delete this directory in case of persistent issues."

**Comment by carotx** [comment]
> Can you grab the current song title from the history file and use that for your display?
>
> READMe: "When using the application, you may notice that certain information will be saved to ~/.local/share/SongRec (or an equivalent directory depending on your operating system), including the CSV-format list of the last recognized songs and the last selected microphone input device (so that it is chosen back when restarting the app). You may want to delete this directory in case of persistent issues."

My bad, I had not seen this paragraph. Obviously this is the solution.
Thank you!
