### ISSUE TITLE
my speakers instead of microphone on doesnt works on pipewire 

### ISSUE THREAD

**Issue by pinokaille** [marin-m/SongRec#58]

**Comment by marin-m** [comment]
Hello,

Is the check box option not displaying at all, or is the check box displaying without effect with clicking?

If the `pactl` command is available on your system, can you please share the output of the `pactl list sources` command?

Thank you!

**Comment by pinokaille** [comment]
> Hello,
> 
> Is the check box option not displaying at all, or is the check box displaying without effect with clicking?
> 
> If the `pactl` command is available on your system, can you please share the output of the `pactl list sources` command?
> 
> Thank you!

The box is displayed but it does nothing at all

Output of `pactl list sources`

`Source #65580
	State: SUSPENDED
	Name: alsa_output.pci-0000_01_00.1.hdmi-stereo-extra1.monitor
	Description: Monitor of GP107GL High Definition Audio Controller Digital Stereo (HDMI 2)
	Driver: PipeWire
	Sample Specification: s32le 2ch 48000Hz
	Channel Map: front-left,front-right
	Owner Module: 4294967295
	Mute: no
	Volume: front-left: 65536 / 100% / 0,00 dB,   front-right: 65536 / 100% / 0,00 dB
	        balance 0,00
	Base Volume: 65536 / 100% / 0,00 dB
	Monitor of Sink: alsa_output.pci-0000_01_00.1.hdmi-stereo-extra1
	Latency: 0 usec, configured 0 usec
	Flags: HARDWARE DECIBEL_VOLUME LATENCY 
	Properties:
		object.path = "alsa:pcm:1:hdmi:1,1:playback"
		api.alsa.path = "hdmi:1,1"
		api.alsa.pcm.card = "1"
		api.alsa.pcm.stream = "playback"
		audio.channels = "2"
		audio.position = "FL,FR"
		device.routes = "1"
		alsa.resolution_bits = "16"
		device.api = "alsa"
		device.class = "sound"
		alsa.class = "generic"
		alsa.subclass = "generic-mix"
		alsa.name = "HDMI 1"
		alsa.id = "HDMI 1"
		alsa.subdevice = "0"
		alsa.subdevice_name = "subdevice #0"
		alsa.device = "7"
		alsa.card = "1"
		alsa.card_name = "HDA NVidia"
		alsa.long_card_name = "HDA NVidia at 0xa3080000 irq 17"
		alsa.driver_name = "snd_hda_intel"
		device.profile.name = "hdmi-stereo-extra1"
		device.profile.description = "Digital Stereo (HDMI 2)"
		card.profile.device = "9"
		device.id = "39"
		factory.name = "api.alsa.pcm.sink"
		priority.driver = "568"
		priority.session = "568"
		media.class = "Audio/Sink"
		node.nick = "HDA NVidia"
		node.name = "alsa_output.pci-0000_01_00.1.hdmi-stereo-extra1"
		device.description = "GP107GL High Definition Audio Controller Digital Stereo (HDMI 2)"
		device.icon_name = "audio-card-hdmi"
		node.pause-on-idle = "false"
		factory.id = "18"
		client.id = "32"
		node.driver = "true"
		factory.mode = "merge"
		audio.adapt.follower = ""
		library.name = "audioconvert/libspa-audioconvert"
		object.id = "44"
	Formats:
		pcm

Source #65581
	State: IDLE
	Name: alsa_output.usb-Blue_Microphones_Yeti_Stereo_Microphone_797_2020_06_26_38347-00.analog-stereo.monitor
	Description: Monitor of Yeti Stereo Microphone Stéréo analogique
	Driver: PipeWire
	Sample Specification: s16le 2ch 48000Hz
	Channel Map: front-left,front-right
	Owner Module: 4294967295
	Mute: no
	Volume: front-left: 65536 / 100% / 0,00 dB,   front-right: 65536 / 100% / 0,00 dB
	        balance 0,00
	Base Volume: 65536 / 100% / 0,00 dB
	Monitor of Sink: alsa_output.usb-Blue_Microphones_Yeti_Stereo_Microphone_797_2020_06_26_38347-00.analog-stereo
	Latency: 0 usec, configured 0 usec
	Flags: HARDWARE DECIBEL_VOLUME LATENCY 
	Properties:
		object.path = "alsa:pcm:2:front:2:playback"
		api.alsa.path = "front:2"
		api.alsa.pcm.card = "2"
		api.alsa.pcm.stream = "playback"
		audio.channels = "2"
		audio.position = "FL,FR"
		device.routes = "1"
		alsa.resolution_bits = "16"
		device.api = "alsa"
		device.class = "sound"
		alsa.class = "generic"
		alsa.subclass = "generic-mix"
		alsa.name = "USB Audio"
		alsa.id = "USB Audio"
		alsa.subdevice = "0"
		alsa.subdevice_name = "subdevice #0"
		alsa.device = "0"
		alsa.card = "2"
		alsa.card_name = "Yeti Stereo Microphone"
		alsa.long_card_name = "Blue Microphones Yeti Stereo Microphone at usb-0000:00:14.0-9, full speed"
		alsa.driver_name = "snd_usb_audio"
		device.profile.name = "analog-stereo"
		device.profile.description = "Stéréo analogique"
		card.profile.device = "4"
		device.id = "40"
		factory.name = "api.alsa.pcm.sink"
		priority.driver = "881"
		priority.session = "881"
		media.class = "Audio/Sink"
		node.nick = "Yeti Stereo Microphone"
		node.name = "alsa_output.usb-Blue_Microphones_Yeti_Stereo_Microphone_797_2020_06_26_38347-00.analog-stereo"
		device.description = "Yeti Stereo Microphone Stéréo analogique"
		device.icon_name = "audio-card-analog"
		node.pause-on-idle = "false"
		factory.id = "18"
		client.id = "32"
		node.driver = "true"
		factory.mode = "merge"
		audio.adapt.follower = ""
		library.name = "audioconvert/libspa-audioconvert"
		object.id = "45"
		node.max-latency = "65536/48000"
	Formats:
		pcm

Source #46
	State: RUNNING
	Name: alsa_input.usb-Blue_Microphones_Yeti_Stereo_Microphone_797_2020_06_26_38347-00.analog-stereo
	Description: Yeti Stereo Microphone Stéréo analogique
	Driver: PipeWire
	Sample Specification: s16le 2ch 48000Hz
	Channel Map: front-left,front-right
	Owner Module: 4294967295
	Mute: no
	Volume: front-left: 60694 /  93% / -2,00 dB,   front-right: 60694 /  93% / -2,00 dB
	        balance 0,00
	Base Volume: 38295 /  58% / -14,00 dB
	Monitor of Sink: n/a
	Latency: 0 usec, configured 0 usec
	Flags: HARDWARE HW_MUTE_CTRL HW_VOLUME_CTRL DECIBEL_VOLUME LATENCY 
	Properties:
		object.path = "alsa:pcm:2:front:2:capture"
		api.alsa.path = "front:2"
		api.alsa.pcm.card = "2"
		api.alsa.pcm.stream = "capture"
		audio.channels = "2"
		audio.position = "FL,FR"
		device.routes = "1"
		alsa.resolution_bits = "16"
		device.api = "alsa"
		device.class = "sound"
		alsa.class = "generic"
		alsa.subclass = "generic-mix"
		alsa.name = "USB Audio"
		alsa.id = "USB Audio"
		alsa.subdevice = "0"
		alsa.subdevice_name = "subdevice #0"
		alsa.device = "0"
		alsa.card = "2"
		alsa.card_name = "Yeti Stereo Microphone"
		alsa.long_card_name = "Blue Microphones Yeti Stereo Microphone at usb-0000:00:14.0-9, full speed"
		alsa.driver_name = "snd_usb_audio"
		device.profile.name = "analog-stereo"
		device.profile.description = "Stéréo analogique"
		card.profile.device = "0"
		device.id = "40"
		factory.name = "api.alsa.pcm.source"
		priority.driver = "1881"
		priority.session = "1881"
		media.class = "Audio/Source"
		node.nick = "Yeti Stereo Microphone"
		node.name = "alsa_input.usb-Blue_Microphones_Yeti_Stereo_Microphone_797_2020_06_26_38347-00.analog-stereo"
		device.description = "Yeti Stereo Microphone Stéréo analogique"
		device.icon_name = "audio-input-microphone-analog"
		node.pause-on-idle = "false"
		factory.id = "18"
		client.id = "32"
		node.driver = "true"
		factory.mode = "split"
		audio.adapt.follower = ""
		library.name = "audioconvert/libspa-audioconvert"
		object.id = "46"
		node.max-latency = "65536/48000"
	Ports:
		analog-input-mic: Microphone (type: Mic, priority: 8700, availability unknown)
	Active Port: analog-input-mic
	Formats:
		pcm`

**Comment by marin-m** [comment]
Hello,

Can you open the `pavucontrol` utility (available in the repositories of your distribution) while SongRec is still open, go to the "Recording" (Enregistrement) tab, and click the combo box that should be displaying "`Yeti Stereo Microphone Stéréo analogique`" to select "`Monitor of GP107GL High Definition Audio Controller Digital Stereo (HDMI 2)`" instead for SongRec?

This should basically be doing the same thing as if you where checking "Recognize from the speakers instead of microphone" in the application. Does it work better?

When you are telling that "Nothing happens at all", does it mean that the sound is still being captured and recognized from your microphone (as the volume gauge in the interface should indicate) as if you didn't check the checkbox, or does it mean that no sound is detected by the application at all?

Does normally recognizing songs from your microphone at least works?

Finally, if you have Audacity installed, does setting the Monitor device (your speakers) as the audio source using `pavucontrol` (like you could do with SongRec, as explained above) allows to record the sound output to your speakers?

Thank you!

**Comment by p5nbTgip0r** [comment]
I'm having the same issue.

> Can you open the `pavucontrol` utility (available in the repositories of your distribution) while SongRec is still open, go to the "Recording" (Enregistrement) tab, and click the combo box that should be displaying "`Yeti Stereo Microphone Stéréo analogique`" to select "`Monitor of GP107GL High Definition Audio Controller Digital Stereo (HDMI 2)`" instead for SongRec?
> 
> This should basically be doing the same thing as if you where checking "Recognize from the speakers instead of microphone" in the application. Does it work better?

Yes, for me this causes the speaker audio to be recorded instead of the microphone and I'm able to recognize songs with just my desktop audio now. I was initially using [Helvum](https://gitlab.freedesktop.org/ryuukyu/helvum/) to disconnect SongRec's input from my microphone capture and then connect my speaker monitors to SongRec's input:
![1](https://user-images.githubusercontent.com/32445075/130265780-de95a8b8-aa0f-4dc2-a854-b2696bbd8ce3.png)
![2](https://user-images.githubusercontent.com/32445075/130265791-63a2f530-71f3-4900-8b13-76a47ad3dacd.png)

The approach I had of using Helvum worked, but was not ideal since I had to convert stereo to mono (my microphone is mono, so SongRec was creating a mono input which I had to use. Using `pavucontrol` gives SongRec stereo inputs) and it requires more steps than using `pavucontrol`.

This is how Helvum looks when changing the input of SongRec to my speaker monitors using `pavucontrol`:
![3](https://user-images.githubusercontent.com/32445075/130268176-449c2781-06ae-4d96-945c-577246c892c5.png)

> When you are telling that "Nothing happens at all", does it mean that the sound is still being captured and recognized from your microphone (as the volume gauge in the interface should indicate) as if you didn't check the checkbox, or does it mean that no sound is detected by the application at all?
> 
> Does normally recognizing songs from your microphone at least works?

In my case, sound is picked up from my microphone. Using the checkbox doesn't change the audio input to my speakers and is always listening from my microphone instead. Recognizing songs from my microphone works, despite the checkbox not doing anything.

> Finally, if you have Audacity installed, does setting the Monitor device (your speakers) as the audio source using pavucontrol (like you could do with SongRec, as explained above) allows to record the sound output to your speakers?

This appears to be the case as well. Switching the audio input to the speaker monitor allows me to record my desktop audio.

Thank you!

**Comment by marin-m** [comment]
Hello,

Ok, could you please attempt to follow this procedure (this is exactly what SongRec normally does when you hit the checkbox) and copy the whole terminal output for debugging purposes (under ```` ``` ``` ````):

* Launch the GUI of the program normally (while recording from the microphone, not checking the checkbox)
* Run: `pactl list short source-outputs`
* Run: `pactl list short sources`
* Run: `pactl list short clients`
* Find the line of `pactl list short source-outputs` where field #3 (client ID) corresponds of a line of `pactl list short clients` where field #1 (client ID) is the same and field #3 (program name) corresponds to `songrec`
* Find the line of `pactl list short sources` where field #2 (device name) contains `.monitor`
* Run the following command: `pactl move-source-output SOURCE_OUTPUT_ID SOURCE_ID`, where you would replace `SOURCE_OUTPUT_ID` with the number from field #1 of the line of `pactl list short source-outputs` that you selected, and you would replace `SOURCE_ID` with the number from field #1 of the line of `pactl list short sources` that you selected.

In a working (non-PipeWire) setup, this should effectively produce something like this:

```
$ pactl list short source-outputs
1933	1	457	protocol-native.c	float32le 2ch 44100Hz

$ pactl list short sources
0	alsa_output.pci-0000_00_1f.3.analog-stereo.monitor	module-alsa-card.c	s16le 2ch 44100Hz	RUNNING
1	alsa_input.pci-0000_00_1f.3.analog-stereo	module-alsa-card.c	s16le 2ch 44100Hz	SUSPENDED

$ pactl list short clients
0	module-systemd-login.c	(null)
4	module-x11-xsmp.c	(null)
5	protocol-native.c	gnome-shell
6	protocol-native.c	gsd-media-keys
7	protocol-native.c	gnome-terminal-server
8	protocol-native.c	gsd-media-keys
9	protocol-native.c	gnome-shell
10	protocol-native.c	geany
11	protocol-native.c	update-notifier
12	protocol-native.c	python3.8
13	protocol-native.c	gsd-power
20	protocol-native.c	gnome-control-center
21	protocol-native.c	gnome-control-center
22	protocol-native.c	system-crash-notification
57	protocol-native.c	soffice.bin
62	protocol-native.c	nautilus
72	protocol-native.c	eog
99	protocol-native.c	totem
100	protocol-native.c	totem
318	protocol-native.c	evince
435	protocol-native.c	firefox
436	protocol-native.c	firefox
437	protocol-native.c	firefox
439	protocol-native.c	sd_espeak-ng
440	protocol-native.c	sd_dummy
441	protocol-native.c	sd_generic
442	protocol-native.c	sd_generic
450	protocol-native.c	songrec
457	protocol-native.c	songrec
520	protocol-native.c	pactl

$ pactl move-source-output 1933 0
```

Thank you!

**Comment by p5nbTgip0r** [comment]
```
$ pactl list short source-outputs          
463     57      306     PipeWire        float32le 2ch 44100Hz
$ pactl list short sources                 
65592   alsa_output.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.analog-stereo.monitor      PipeWire        s16le 2ch 48000Hz       IDLE
57      alsa_input.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.mono-fallback       PipeWire        s16le 1ch 48000Hz       RUNNING
$ pactl list short clients                 
32      PipeWire        pipewire-media-session
33      PipeWire        pipewire-media-session
328     PipeWire        latte-dock
377     PipeWire        code
338     PipeWire        xdg-desktop-portal
207     PipeWire        latte-dock
371     PipeWire        electron
345     PipeWire        electron
66      PipeWire        steam
359     PipeWire        firefox
369     PipeWire        firefox
483     PipeWire        firefox
351     PipeWire        songrec
306     PipeWire        songrec
438     PipeWire        pactl
$ pactl move-source-output 463 65592       
Failure: No such entity
$ 
```

On the last command, I tried to use tab completion in zsh and it appears that replacing `SOURCE_ID` with the name of the source works:
```
$ pactl move-source-output 463 alsa_output.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.analog-stereo.monitor       
$ 
```

With using the source name instead of the source ID, SongRec now records from the speakers instead of the microphone.

**Comment by marin-m** [comment]
Hello,

It should be fixed with version 0.2.0, which was released some time ago, can you please confirm?

Regards,

**Comment by p5nbTgip0r** [comment]
Yes, it appears to work now. Thank you!

**Comment by frainz-de** [comment]
I just had the exact same issue and only found it by looking through the closed issues of the project. Should we maybe have a troubleshooting section in the README?

**Comment by marin-m** [comment]
Hello,

This should not happen anymore.

Can you please tell which version of SongRec you are using and where you installed it?

**Comment by frainz-de** [comment]
I'm using SongRec 0.2.1-1 from the Manjaro repositories. Before I changed the default input to the monitor of my speakers, it was attaching itself to the monitor of my HDMI output when using the checkbox.
Interestingly, the checkbox to switch between speakers and microphone disappears when a monitor is the default in pavucontrol
