### ISSUE TITLE
2 Songrec instances : No match for this song

### ISSUE THREAD

**Issue by aaaaadrien** [marin-m/SongRec#59]
Hello,

Platform 1 : Calculate Linux 21 - Flatpak 1.10.2
Platform 2 : Linux Mint 19.3 - Flatpak 1.0.9

`Name                            Application ID                               Version           Branch          Installation`
`SongRec                         com.github.marinm.songrec                    0.1.8             stable          system`

**Step to reproduce :** 
Open 1 songrec instance
Listen music
Open second songrec instance
(Eventually Close the second instance)
Message "No Match for this song" pop several times, unable to stop theses messages while one instance of songrec started)

No problem if 1 instance of songrec is started (no message with songrec used for long long hours before i see the bug)

Can you fix it or don't start second instance of songrec if 1 already started ?

Thanks

**Comment by marin-m** [comment]
Hello YouTubeur célèbre,

Thanks for noticing. I have pushed a fix in commit b22ad2d and I plan to make a release soon in order to integrate the French and Dutch translations as well.

Regards,

**Comment by aaaaadrien** [comment]
Thanks ! 
I will test when released !

**Comment by marin-m** [comment]
Hello,

It should be fixed with version 0.1.9, which was released some time ago, can you please confirm?

Regards,

**Comment by aaaaadrien** [comment]
Now i can't start 2 Songrec instances. So fixed.
I am shocked, the software is now in french :D Good job
