### ISSUE TITLE
More on peak detection

### ISSUE THREAD

**Issue by AlekseyMartynov** [marin-m/SongRec#6]
Hello, it's me again

I became really obsessive with figuring out how Shazam actually picks peaks. So I went data-driven. I captured many signatures from the official app and explored the distance between peaks. Having analyzed 16,000 peaks, I found 2 empty areas around each:
- ±47 time units
- ±9 freq bins by ±3 time units rectangle

These parameters produce quite dense constellations:
![spectro1](https://user-images.githubusercontent.com/4426185/98021053-dc5a0b80-1e14-11eb-989f-4edf6f5f3a77.png)

Obviously, only most intense peaks are wanted. But what should be the threshold? Intuitively, I didn't like absolute or relative magnitude because a single noise spike can spoil the entire spectrogram. Then I noticed that in original signatures, the number of peaks is often limited by approx 12 × sample duration:

```
sample len: 4.19
peaks in band 0: 14
peaks in band 1: 48
peaks in band 2: 48

sample len: 14.6
peaks in band 0: 63
peaks in band 1: 168
peaks in band 2: 168
```

This made me think of a rate limiter. After a bit of trial and error, I wrote a specialized rate limiter ([code](https://github.com/AlekseyMartynov/shazam-for-real/blob/384f43e0ee84b38711c1e244a71131abf8a565bb/LandmarkFinder.cs#L94-L111)). When the next peak doesn't fit, the algorithm checks if there is a less intense peak among previously recorded. If found, it is replaced with the new peak, otherwise the new peak is rejected.

For 12 peaks per second per band, spectrograms look like this:
![spectro2](https://user-images.githubusercontent.com/4426185/98022415-a584f500-1e16-11eb-9783-1a23214d37c0.png)

Recognition worked fairly well.

Then I tried the lowest limit of 1. And you know what? It worked too. These 20 points were correctly tagged as Smells Like Teen Spirit:
![spectro3](https://user-images.githubusercontent.com/4426185/98023035-6c995000-1e17-11eb-85ae-85a9bfc73f6a.png)

Maybe you'll want to check this approach in your app.
Thank you.

**Comment by AlekseyMartynov** [comment]
FYI @Vest

**Comment by marin-m** [comment]
Thanks for the suggestions. I think that there was some code in the original thing that did sorting and filtering of the frequency points but I skipped it because it worked without it. This should be some optimization compensated anyway by the server-side processing I think.

**Comment by AlekseyMartynov** [comment]
I believe that servers truncate excessive data. This is what common sense suggests - why would they want extra server load? Also, I noticed that dense signatures (several hundred points per band) have worse accuracy. This is why I started my research in the first place.

**Comment by marin-m** [comment]
More than needing it to save computational power, I think that there are odds that the client-side algorithm would simply closely mirror the original server-side algorithm that should be designed to reduce the general complexity of the tree/graph of peaks used to recognize known songs, in order to save both storage space and traversal time over the known songs patterns. As the intensity of peaks is included and is a primary information, unimportant peaks can be pruned anyway.

**Comment by AlekseyMartynov** [comment]
>  there are odds that the client-side algorithm would simply closely mirror the original server-side algorithm that should be designed to reduce the general complexity of the tree/graph of peaks used to recognize known songs

I agree. They likely use the exact same code base, with (or even without) conditional compilation.

After further experiments, I found that the real practical difference is that API returns mis-tags faster for dense signatures. But since you always send the maximum length of 12 sec, it does not matter.
