### ISSUE TITLE
Using SongRec's implementation in my own app.

### ISSUE THREAD

**Issue by Marekkon5** [marin-m/SongRec#66]
Hello, I would like to ask, whether I could use your fingerprinting and signature algorithms in my app - OneTagger (https://github.com/Marekkon5/onetagger), since you don't release this as a library, but as a standalone app. My app is using the Apache license, however I could switch to GPL as well. I am asking because I would practically copy the functionality of your app into mine, but with some other features as well. Thanks

**Comment by marin-m** [comment]
Hello,

I think I see no problem, it's Shazam's logic originally anyway. I have no problem about the app using the Apache license neither.

Regards
