### ISSUE TITLE
I seem to have selected a sound stream input source which was invalid and now crash on boot.

### ISSUE THREAD

**Issue by NeedAboutTreeFiddy** [marin-m/SongRec#79]
Reinstall does not resolved the issue.

**Comment by marin-m** [comment]
Hello,

On which operating system? Did you use Flatpak to install SongRec?

If you are on Linux, does deleting the `.local/share/SongRec/device_name.txt` file under your `HOME` directory solve the issue?

Regards,

**Comment by NeedAboutTreeFiddy** [comment]
Manjaro KDE Plasma Version 5.23.3
![image](https://user-images.githubusercontent.com/32823556/142954405-3502f712-8ed9-4f86-8148-fb7aaf573cf4.png)
Yeah! I deleted and now it opens.
![image](https://user-images.githubusercontent.com/32823556/142954632-e211f89f-8d5e-4a50-adcd-4f3da2f7a9dc.png)
