### ISSUE TITLE
What database(s) does this check for song information?

### ISSUE THREAD

**Issue by staysh** [marin-m/SongRec#8]
Very cool project!

Was just wondering what database is used to identify songs and how one would go about adding songs that don't get identified.

**Comment by staysh** [comment]
Nevermind, I looked at the code. Looks like it goes to a shazam api?

**Comment by marin-m** [comment]
Hello,

Yes, this contacts Shazam. It sends only information about the prominent frequency peaks of a song, as Shazam does.
