### ISSUE TITLE
Cooperation request

### ISSUE THREAD

**Issue by TriskGit** [marin-m/SongRec#83]
Hello Marin, we have a project which looks to leverage Shazam capability in a different way. Looking for a paid collaborator...

Are you interested? 

Yuri.

yuri@vizitei.com

**Comment by marin-m** [comment]
Thank you for your proposal!

I am already full-time employed, not looking actively to change and prefer to stay working for a French company (for language, geographic and administrative reasons).

Regards,

**Comment by TriskGit** [comment]
Main, 

 

Thank you for a fast response. 

 

I understand. 

 

I was actually looking for more of project help – consulting for your expertise regarding Shazam functionality. Part time. 

 

Regards, 

 

Yuri.

 

Yuri Vizitei

 ***@***.***> ***@***.***

Skype: Vizitei

To book a call:

 <https://calendly.com/vizitei> https://calendly.com/vizitei
