### ISSUE TITLE
Doesn't work with .wma files

### ISSUE THREAD

**Issue by pedrofleck** [marin-m/SongRec#9]
I tried to recognize a song with a .wma format and it didn't work. I can play the song without any problem outside of it.

On a side note: does it work with video files? I tried with one and it didn't recognize the song, but it didn't give me the "Unrecognized format" error.

**Comment by marin-m** [comment]
Hello,

For now, the only recognized formats are `.wav`, `.flac`, `.ogg`, `.mp3` whose decoding is provided by the [`rodio`](https://github.com/RustAudio/rodio) library.

I think that I should use something like [`rust-ffmpeg`](https://github.com/zmwangx/rust-ffmpeg) (which has an example of [transcoding audio](https://github.com/zmwangx/rust-ffmpeg/blob/master/examples/transcode-audio.rs) which can likely be stripped out of some code and modified to output to a memory buffer) to support more formats.

**Comment by YellowSub17** [comment]
Hello, thanks for a great program.
I was having a problem reading the ACC+ radio [stream files](https://radio.abc.net.au/help/streams#!) listed here, so I wrote a bash script to record a 15 second snippet of a file with VLC, save that as a .wav, and use that file for songrec. Here is the script, maybe it could help with your .wma problems @pedrofleck ?

[getsong.txt](https://github.com/marin-m/SongRec/files/5943293/getsong.txt)

**Comment by marin-m** [comment]
Hello,

FYI the version 0.1.6 that I deployed this morning should add support for any format supported by FFMpeg, including .MP4/.AAC or .WMA, as well as video formats, as well as FFMpeg is installed on the system (it has been added as a dependency of the Ubuntu and Archlinux package and is commonly installed elsewhere).

This should address the issue.

Have a good day
