### ISSUE TITLE
Open/Search on YouTube is broken on Linux

### ISSUE THREAD

**Issue by mustarde** [marin-m/SongRec#92]
When I want to open or search the song on YouTube I get a crash on Arch Linux. I guess it is about Wayland.
```
$ songrec
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { domain: g-io-error-quark, code: 15, message: "Operation not supported" }', src/gui/main_window.rs:399:64
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by marin-m** [comment]
Hello,

Did you install the application through Flatpak?

Regards,

**Comment by mustarde** [comment]
Hi, 
No it's from Arch's community repo.

`1 community/songrec 0.3.2-1 (2.0 MiB 7.0 MiB)
    An open-source, unofficial Shazam client for Linux
`

But now it all works fine. I don't know what was wrong before.
